"""Build NotebookCells from tool execution results.

This module sits between the agent runner and the notebook orchestrator.
After a tool executes code in the sandbox, the cell builder constructs
a properly annotated ``NotebookCell`` that captures:

  - the executed code
  - a text/plain summary of the result
  - CellMetadata breadcrumbs (purpose, produces, depends_on)

The runner calls ``build_cell_from_tool_result()`` after each successful
tool execution, then passes the cell to the orchestrator for persistence.
"""
from __future__ import annotations

import ast
import logging
from typing import Any

import pandas as pd

from backend.notebook.models import (
    CellMetadata,
    CellOutput,
    NotebookCell,
    utcnow_iso,
)

logger = logging.getLogger(__name__)

# Maximum length for result summary stored in cell output.
_MAX_SUMMARY_LEN = 500


def build_cell_from_tool_result(
    *,
    code: str,
    tool_name: str,
    result: Any,
    plan_step: str = "",
    execution_count: int | None = None,
    artifact_ids: list[str] | None = None,
    new_variables: list[str] | None = None,
) -> NotebookCell:
    """Construct a NotebookCell from a completed tool execution.

    Parameters
    ----------
    code
        The Python/SQL code that was executed.
    tool_name
        Name of the tool (``pandas_tool``, ``plotly_tool``, etc.).
    result
        The raw result returned by ``sandbox.execute()``.
    plan_step
        One-line description from the agent's plan (becomes ``purpose``).
    execution_count
        Sequential cell execution number.
    artifact_ids
        IDs of artifacts produced by this execution.
    new_variables
        Variable names created during execution.
    """
    # Determine cell tags based on tool.
    tags = _tags_for_tool(tool_name)
    language = "sql" if tool_name == "sql_tool" else "python"

    # Extract question for SQL tools.
    question = ""
    if tool_name == "sql_tool" and isinstance(result, tuple):
        question = plan_step

    # Build breadcrumbs.
    produces = list(new_variables or [])
    depends_on = _extract_variable_refs(code) if language == "python" else []

    metadata = CellMetadata(
        purpose=plan_step or f"{tool_name} execution",
        produces=produces,
        depends_on=depends_on,
        tool_name=tool_name,
        idempotent=True,
        created_by="llm",
        created_at=utcnow_iso(),
        language=language,
        question=question,
        artifact_refs=artifact_ids or [],
        tags=tags,
    )

    # Build source with inline breadcrumb comments.
    annotated_source = _annotate_source(code, metadata)

    # Build output.
    summary = _summarize_result(result)
    outputs: list[CellOutput] = []
    if summary:
        outputs.append(
            CellOutput(
                output_type="execute_result",
                data={"text/plain": summary},
                execution_count=execution_count,
            )
        )

    return NotebookCell(
        cell_type="code",
        source=annotated_source,
        metadata=metadata,
        outputs=outputs,
        execution_count=execution_count,
    )


def build_source_binding_cell(
    *,
    alias: str,
    variable_name: str,
    source_type: str,
    display_name: str,
    load_code: str,
) -> NotebookCell:
    """Build a source_binding cell for a data source.

    These cells are generated by the system (not the LLM) when a source
    is added to the session.
    """
    metadata = CellMetadata(
        purpose=f"Load source: {display_name}",
        produces=[variable_name],
        depends_on=[],
        source_alias=alias,
        tool_name="",
        idempotent=True,
        created_by="system",
        created_at=utcnow_iso(),
        tags=["source_binding"],
    )

    annotated = _annotate_source(load_code, metadata)

    return NotebookCell(
        cell_type="code",
        source=annotated,
        metadata=metadata,
    )


def build_preamble_cell(session_id: str, sources_summary: str = "") -> NotebookCell:
    """Build the markdown preamble cell for a new notebook."""
    lines = ["# Analysis Session"]
    if sources_summary:
        lines.append(f"\n{sources_summary}")

    return NotebookCell(
        cell_type="markdown",
        source="\n".join(lines),
        metadata=CellMetadata(
            purpose="Session preamble",
            created_by="system",
            created_at=utcnow_iso(),
            tags=["preamble"],
        ),
    )


# ── Helpers ──────────────────────────────────────────────────────────────────


def _tags_for_tool(tool_name: str) -> list[str]:
    if tool_name == "plotly_tool":
        return ["visualization"]
    if tool_name in ("pandas_tool", "value_tool", "sql_tool"):
        return ["analysis"]
    if tool_name == "search_tool":
        return ["search"]
    return ["analysis"]


def _annotate_source(code: str, meta: CellMetadata) -> str:
    """Prepend structured comments to cell source."""
    comments: list[str] = []
    if meta.purpose:
        comments.append(f"# PURPOSE: {meta.purpose}")
    if meta.produces:
        comments.append(f"# PRODUCES: {', '.join(meta.produces)}")
    if meta.depends_on:
        comments.append(f"# DEPENDS_ON: {', '.join(meta.depends_on)}")
    if not meta.idempotent:
        comments.append("# IDEMPOTENT: false")

    if comments:
        return "\n".join(comments) + "\n" + code
    return code


def _extract_variable_refs(code: str) -> list[str]:
    """Extract referenced variable names from Python code via AST.

    Returns names that are loaded (read) but not defined in this code.
    This is a best-effort heuristic, not a full scope analysis.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return []

    loaded: set[str] = set()
    stored: set[str] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            if isinstance(node.ctx, ast.Load):
                loaded.add(node.id)
            elif isinstance(node.ctx, (ast.Store, ast.Del)):
                stored.add(node.id)

    # Filter out builtins and standard modules.
    skip = {
        "pd", "np", "px", "go", "chart", "print", "len", "range",
        "list", "dict", "str", "int", "float", "bool", "set", "tuple",
        "True", "False", "None", "tool_result", "result",
    }
    refs = sorted(loaded - stored - skip)
    return refs


def _summarize_result(result: Any) -> str:
    """Create a compact text summary of a tool result."""
    if result is None:
        return ""

    if isinstance(result, pd.DataFrame):
        return f"DataFrame({result.shape[0]} rows, {result.shape[1]} cols)"

    if isinstance(result, pd.Series):
        return f"Series({len(result)} items)"

    if isinstance(result, dict):
        artifact_type = result.get("artifact_type", "")
        items = result.get("items", {})
        if artifact_type and items:
            names = ", ".join(str(k) for k in list(items.keys())[:5])
            return f"{artifact_type}: {names}"

    text = str(result)
    if len(text) > _MAX_SUMMARY_LEN:
        return text[:_MAX_SUMMARY_LEN] + "…"
    return text
