-- Demo finance datasets loaded from Excel. Generated for local demo only.

CREATE SCHEMA IF NOT EXISTS demo;

DROP TABLE IF EXISTS demo."manual_plan";

CREATE TABLE demo."manual_plan" (
    "extra_1" TEXT,
    "ошибки" TEXT,
    "домен" TEXT,
    "домен_корр" TEXT,
    "бе" TEXT,
    "бе_корр" TEXT,
    "цфо" TEXT,
    "мвз" TEXT,
    "суперпродукт" TEXT,
    "продукт_1с_ух" TEXT,
    "фин_клиент" TEXT,
    "ключевой_клиент" TEXT,
    "направление" TEXT,
    "екдр" TEXT,
    "pl_ручной_ввод" TEXT,
    "статья_pl" TEXT,
    "организация" TEXT,
    "домен_от_контрагента" TEXT,
    "бе_от_контрагента" TEXT,
    "контрагент" TEXT,
    "l_контрагент_1с_ух" TEXT,
    "id_сделки" TEXT,
    "бизнес_категория" TEXT,
    "проект" TEXT,
    "l_проект_1с_ух" TEXT,
    "проект_1с_ух_наименование" TEXT,
    "тип_проекта_1с_ух" TEXT,
    "комментарий" TEXT,
    "отв" TEXT,
    "ставка_ндс" NUMERIC,
    "не_рассчитывать_cf" TEXT,
    "cf_поквартально" TEXT,
    "cf_в_каком_месяце_признавать" TEXT,
    "смещение_сумм_cf_мес" BIGINT,
    "pl_jan" NUMERIC,
    "pl_feb" NUMERIC,
    "pl_mar" NUMERIC,
    "pl_apr" NUMERIC,
    "pl_may" NUMERIC,
    "pl_jun" NUMERIC,
    "pl_jul" NUMERIC,
    "pl_aug" NUMERIC,
    "pl_sep" NUMERIC,
    "pl_oct" NUMERIC,
    "pl_nov" NUMERIC,
    "pl_dec" NUMERIC,
    "pl_fy" NUMERIC,
    "статья_cf_кодификатор" TEXT,
    "статья_cf_корректировка" TEXT,
    "статья_cf" TEXT,
    "cf_jan" NUMERIC,
    "cf_feb" NUMERIC,
    "cf_mar" NUMERIC,
    "cf_apr" NUMERIC,
    "cf_may" NUMERIC,
    "cf_jun" NUMERIC,
    "cf_jul" NUMERIC,
    "cf_aug" NUMERIC,
    "cf_sep" NUMERIC,
    "cf_oct" NUMERIC,
    "cf_nov" NUMERIC,
    "cf_dec" NUMERIC,
    "cf_fy" NUMERIC,
    "extra_64" BIGINT,
    "extra_65" TEXT,
    "extra_66" NUMERIC,
    "extra_67" NUMERIC,
    "extra_68" TEXT
);

\copy demo."manual_plan" ("extra_1", "ошибки", "домен", "домен_корр", "бе", "бе_корр", "цфо", "мвз", "суперпродукт", "продукт_1с_ух", "фин_клиент", "ключевой_клиент", "направление", "екдр", "pl_ручной_ввод", "статья_pl", "организация", "домен_от_контрагента", "бе_от_контрагента", "контрагент", "l_контрагент_1с_ух", "id_сделки", "бизнес_категория", "проект", "l_проект_1с_ух", "проект_1с_ух_наименование", "тип_проекта_1с_ух", "комментарий", "отв", "ставка_ндс", "не_рассчитывать_cf", "cf_поквартально", "cf_в_каком_месяце_признавать", "смещение_сумм_cf_мес", "pl_jan", "pl_feb", "pl_mar", "pl_apr", "pl_may", "pl_jun", "pl_jul", "pl_aug", "pl_sep", "pl_oct", "pl_nov", "pl_dec", "pl_fy", "статья_cf_кодификатор", "статья_cf_корректировка", "статья_cf", "cf_jan", "cf_feb", "cf_mar", "cf_apr", "cf_may", "cf_jun", "cf_jul", "cf_aug", "cf_sep", "cf_oct", "cf_nov", "cf_dec", "cf_fy", "extra_64", "extra_65", "extra_66", "extra_67", "extra_68") FROM '/demo-data/manual_plan.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8', NULL '\N')

DROP TABLE IF EXISTS demo."uh_receipts_2026_03";

CREATE TABLE demo."uh_receipts_2026_03" (
    "номер_документа" TEXT,
    "дата_документа" TEXT,
    "вид_операции" TEXT,
    "контрагент" TEXT,
    "инн_контрагента" BIGINT,
    "кпп_контрагента" BIGINT,
    "договор" TEXT,
    "номер_договора" TEXT,
    "регистрационный_номер_договора" TEXT,
    "дата_регистрации_договора" TEXT,
    "цфо_договор" TEXT,
    "статья_ддс" TEXT,
    "статья_начисления" TEXT,
    "внутренний_номер_в_до" TEXT,
    "источник_договора" TEXT,
    "валюта_документа" TEXT,
    "п_п" BIGINT,
    "номенклатура" TEXT,
    "содержание_услуги" TEXT,
    "этап_проекта_документ" TEXT,
    "цфо_документ" TEXT,
    "ндс" TEXT,
    "ндс_2" NUMERIC,
    "сумма" NUMERIC,
    "сумма_включает_ндс" TEXT,
    "счет_доходов" TEXT,
    "номенклатурная_группа" TEXT,
    "счет_затрат" TEXT,
    "номенклатурная_группа_2" TEXT,
    "статьи_затрат" TEXT
);

\copy demo."uh_receipts_2026_03" ("номер_документа", "дата_документа", "вид_операции", "контрагент", "инн_контрагента", "кпп_контрагента", "договор", "номер_договора", "регистрационный_номер_договора", "дата_регистрации_договора", "цфо_договор", "статья_ддс", "статья_начисления", "внутренний_номер_в_до", "источник_договора", "валюта_документа", "п_п", "номенклатура", "содержание_услуги", "этап_проекта_документ", "цфо_документ", "ндс", "ндс_2", "сумма", "сумма_включает_ндс", "счет_доходов", "номенклатурная_группа", "счет_затрат", "номенклатурная_группа_2", "статьи_затрат") FROM '/demo-data/uh_receipts_2026_03.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8', NULL '\N')
