-- Demo finance datasets loaded from Excel. Generated for local demo only.

CREATE DATABASE IF NOT EXISTS demo;

DROP TABLE IF EXISTS demo.`manual_plan`;

CREATE TABLE demo.`manual_plan` (
    `extra_1` Nullable(String),
    `ошибки` Nullable(String),
    `домен` Nullable(String),
    `домен_корр` Nullable(String),
    `бе` Nullable(String),
    `бе_корр` Nullable(String),
    `цфо` Nullable(String),
    `мвз` Nullable(String),
    `суперпродукт` Nullable(String),
    `продукт_1с_ух` Nullable(String),
    `фин_клиент` Nullable(String),
    `ключевой_клиент` Nullable(String),
    `направление` Nullable(String),
    `екдр` Nullable(String),
    `pl_ручной_ввод` Nullable(String),
    `статья_pl` Nullable(String),
    `организация` Nullable(String),
    `домен_от_контрагента` Nullable(String),
    `бе_от_контрагента` Nullable(String),
    `контрагент` Nullable(String),
    `l_контрагент_1с_ух` Nullable(String),
    `id_сделки` Nullable(String),
    `бизнес_категория` Nullable(String),
    `проект` Nullable(String),
    `l_проект_1с_ух` Nullable(String),
    `проект_1с_ух_наименование` Nullable(String),
    `тип_проекта_1с_ух` Nullable(String),
    `комментарий` Nullable(String),
    `отв` Nullable(String),
    `ставка_ндс` Nullable(Float64),
    `не_рассчитывать_cf` Nullable(String),
    `cf_поквартально` Nullable(String),
    `cf_в_каком_месяце_признавать` Nullable(String),
    `смещение_сумм_cf_мес` Nullable(Int64),
    `pl_jan` Nullable(Float64),
    `pl_feb` Nullable(Float64),
    `pl_mar` Nullable(Float64),
    `pl_apr` Nullable(Float64),
    `pl_may` Nullable(Float64),
    `pl_jun` Nullable(Float64),
    `pl_jul` Nullable(Float64),
    `pl_aug` Nullable(Float64),
    `pl_sep` Nullable(Float64),
    `pl_oct` Nullable(Float64),
    `pl_nov` Nullable(Float64),
    `pl_dec` Nullable(Float64),
    `pl_fy` Nullable(Float64),
    `статья_cf_кодификатор` Nullable(String),
    `статья_cf_корректировка` Nullable(String),
    `статья_cf` Nullable(String),
    `cf_jan` Nullable(Float64),
    `cf_feb` Nullable(Float64),
    `cf_mar` Nullable(Float64),
    `cf_apr` Nullable(Float64),
    `cf_may` Nullable(Float64),
    `cf_jun` Nullable(Float64),
    `cf_jul` Nullable(Float64),
    `cf_aug` Nullable(Float64),
    `cf_sep` Nullable(Float64),
    `cf_oct` Nullable(Float64),
    `cf_nov` Nullable(Float64),
    `cf_dec` Nullable(Float64),
    `cf_fy` Nullable(Float64),
    `extra_64` Nullable(Int64),
    `extra_65` Nullable(String),
    `extra_66` Nullable(Float64),
    `extra_67` Nullable(Float64),
    `extra_68` Nullable(String)
) ENGINE = MergeTree ORDER BY tuple();

INSERT INTO demo.`manual_plan` SELECT * FROM file('demo/manual_plan.csv', 'CSVWithNames', '`extra_1` Nullable(String), `ошибки` Nullable(String), `домен` Nullable(String), `домен_корр` Nullable(String), `бе` Nullable(String), `бе_корр` Nullable(String), `цфо` Nullable(String), `мвз` Nullable(String), `суперпродукт` Nullable(String), `продукт_1с_ух` Nullable(String), `фин_клиент` Nullable(String), `ключевой_клиент` Nullable(String), `направление` Nullable(String), `екдр` Nullable(String), `pl_ручной_ввод` Nullable(String), `статья_pl` Nullable(String), `организация` Nullable(String), `домен_от_контрагента` Nullable(String), `бе_от_контрагента` Nullable(String), `контрагент` Nullable(String), `l_контрагент_1с_ух` Nullable(String), `id_сделки` Nullable(String), `бизнес_категория` Nullable(String), `проект` Nullable(String), `l_проект_1с_ух` Nullable(String), `проект_1с_ух_наименование` Nullable(String), `тип_проекта_1с_ух` Nullable(String), `комментарий` Nullable(String), `отв` Nullable(String), `ставка_ндс` Nullable(Float64), `не_рассчитывать_cf` Nullable(String), `cf_поквартально` Nullable(String), `cf_в_каком_месяце_признавать` Nullable(String), `смещение_сумм_cf_мес` Nullable(Int64), `pl_jan` Nullable(Float64), `pl_feb` Nullable(Float64), `pl_mar` Nullable(Float64), `pl_apr` Nullable(Float64), `pl_may` Nullable(Float64), `pl_jun` Nullable(Float64), `pl_jul` Nullable(Float64), `pl_aug` Nullable(Float64), `pl_sep` Nullable(Float64), `pl_oct` Nullable(Float64), `pl_nov` Nullable(Float64), `pl_dec` Nullable(Float64), `pl_fy` Nullable(Float64), `статья_cf_кодификатор` Nullable(String), `статья_cf_корректировка` Nullable(String), `статья_cf` Nullable(String), `cf_jan` Nullable(Float64), `cf_feb` Nullable(Float64), `cf_mar` Nullable(Float64), `cf_apr` Nullable(Float64), `cf_may` Nullable(Float64), `cf_jun` Nullable(Float64), `cf_jul` Nullable(Float64), `cf_aug` Nullable(Float64), `cf_sep` Nullable(Float64), `cf_oct` Nullable(Float64), `cf_nov` Nullable(Float64), `cf_dec` Nullable(Float64), `cf_fy` Nullable(Float64), `extra_64` Nullable(Int64), `extra_65` Nullable(String), `extra_66` Nullable(Float64), `extra_67` Nullable(Float64), `extra_68` Nullable(String)') SETTINGS format_csv_null_representation='\\N';

DROP TABLE IF EXISTS demo.`uh_receipts_2026_03`;

CREATE TABLE demo.`uh_receipts_2026_03` (
    `номер_документа` Nullable(String),
    `дата_документа` Nullable(String),
    `вид_операции` Nullable(String),
    `контрагент` Nullable(String),
    `инн_контрагента` Nullable(Int64),
    `кпп_контрагента` Nullable(Int64),
    `договор` Nullable(String),
    `номер_договора` Nullable(String),
    `регистрационный_номер_договора` Nullable(String),
    `дата_регистрации_договора` Nullable(String),
    `цфо_договор` Nullable(String),
    `статья_ддс` Nullable(String),
    `статья_начисления` Nullable(String),
    `внутренний_номер_в_до` Nullable(String),
    `источник_договора` Nullable(String),
    `валюта_документа` Nullable(String),
    `п_п` Nullable(Int64),
    `номенклатура` Nullable(String),
    `содержание_услуги` Nullable(String),
    `этап_проекта_документ` Nullable(String),
    `цфо_документ` Nullable(String),
    `ндс` Nullable(String),
    `ндс_2` Nullable(Float64),
    `сумма` Nullable(Float64),
    `сумма_включает_ндс` Nullable(String),
    `счет_доходов` Nullable(String),
    `номенклатурная_группа` Nullable(String),
    `счет_затрат` Nullable(String),
    `номенклатурная_группа_2` Nullable(String),
    `статьи_затрат` Nullable(String)
) ENGINE = MergeTree ORDER BY tuple();

INSERT INTO demo.`uh_receipts_2026_03` SELECT * FROM file('demo/uh_receipts_2026_03.csv', 'CSVWithNames', '`номер_документа` Nullable(String), `дата_документа` Nullable(String), `вид_операции` Nullable(String), `контрагент` Nullable(String), `инн_контрагента` Nullable(Int64), `кпп_контрагента` Nullable(Int64), `договор` Nullable(String), `номер_договора` Nullable(String), `регистрационный_номер_договора` Nullable(String), `дата_регистрации_договора` Nullable(String), `цфо_договор` Nullable(String), `статья_ддс` Nullable(String), `статья_начисления` Nullable(String), `внутренний_номер_в_до` Nullable(String), `источник_договора` Nullable(String), `валюта_документа` Nullable(String), `п_п` Nullable(Int64), `номенклатура` Nullable(String), `содержание_услуги` Nullable(String), `этап_проекта_документ` Nullable(String), `цфо_документ` Nullable(String), `ндс` Nullable(String), `ндс_2` Nullable(Float64), `сумма` Nullable(Float64), `сумма_включает_ндс` Nullable(String), `счет_доходов` Nullable(String), `номенклатурная_группа` Nullable(String), `счет_затрат` Nullable(String), `номенклатурная_группа_2` Nullable(String), `статьи_затрат` Nullable(String)') SETTINGS format_csv_null_representation='\\N';
