use_default_settings: true

general:
  debug: false
  instance_name: "Search Service SearXNG"
  contact_url: false

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "change-this-secret-key-in-production"
  limiter: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "ru"
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_locale: "ru"
  default_theme: simple
  theme_args:
    simple_style: dark

engines:
  - name: brave
    disable: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
