CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    is_admin boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_tokens (
    token_hash text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL
);
CREATE INDEX idx_auth_tokens_user ON auth_tokens(user_id, expires_at);

CREATE TABLE user_settings (
    user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    theme text NOT NULL DEFAULT 'dark',
    default_include_reasoning boolean NOT NULL DEFAULT true,
    default_answer_style text NOT NULL DEFAULT 'detailed',
    analysis_mode text NOT NULL DEFAULT 'fast',
    analysis_depth text NOT NULL DEFAULT 'light',
    llm_temperature_chat double precision NOT NULL DEFAULT 0.7,
    llm_temperature_tool double precision NOT NULL DEFAULT 0.5,
    llm_max_tokens_default integer NOT NULL DEFAULT 4096,
    llm_max_tokens_reasoning integer NOT NULL DEFAULT 4096,
    backend_query_timeout_sec integer NOT NULL DEFAULT 180,
    agent_max_steps integer NOT NULL DEFAULT 32,
    agent_step_timeout_sec integer NOT NULL DEFAULT 45,
    agent_inner_recursion_limit integer NOT NULL DEFAULT 32,
    agent_react_enabled boolean NOT NULL DEFAULT false,
    ui_scale integer NOT NULL DEFAULT 100,
    llm_streaming boolean NOT NULL DEFAULT true,
    show_thinking boolean NOT NULL DEFAULT true,
    show_think_planning boolean NOT NULL DEFAULT true,
    show_think_tool boolean NOT NULL DEFAULT true,
    show_think_final boolean NOT NULL DEFAULT true,
    show_detailed_tool_steps boolean NOT NULL DEFAULT false,
    show_rag_errors boolean NOT NULL DEFAULT true,
    anomaly_check_enabled boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_tool_settings (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tool_key text NOT NULL,
    enabled boolean NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id, tool_key)
);

CREATE TABLE user_skill_settings (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id text NOT NULL,
    enabled boolean NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id, skill_id)
);

CREATE TABLE mcp_server_configs (
    server_id text PRIMARY KEY,
    name text NOT NULL,
    description text,
    transport text NOT NULL,
    url text,
    command text,
    args_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    env_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    tool_bindings_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    timeout_sec double precision NOT NULL DEFAULT 30.0,
    enabled boolean NOT NULL DEFAULT true,
    enabled_by_default boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE mcp_server_secrets (
    server_id text PRIMARY KEY REFERENCES mcp_server_configs(server_id) ON DELETE CASCADE,
    secret_blob_encrypted text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_mcp_server_settings (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    server_id text NOT NULL REFERENCES mcp_server_configs(server_id) ON DELETE CASCADE,
    enabled boolean NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id, server_id)
);

CREATE TABLE user_db_connections (
    id text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name text NOT NULL,
    db_type text NOT NULL,
    host text NOT NULL,
    port integer,
    database_name text,
    username text,
    options_json jsonb,
    last_test_at timestamptz,
    last_test_ok boolean,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(user_id, name)
);
CREATE INDEX idx_user_db_connections_user
    ON user_db_connections(user_id, updated_at DESC);

CREATE TABLE user_db_connection_secrets (
    connection_id text PRIMARY KEY REFERENCES user_db_connections(id) ON DELETE CASCADE,
    secret_blob_encrypted text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_db_connection_access (
    connection_id text NOT NULL REFERENCES user_db_connections(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    granted_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(connection_id, user_id)
);
CREATE INDEX idx_user_db_connection_access_user
    ON user_db_connection_access(user_id, connection_id);

CREATE TABLE user_memories (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mem_type text NOT NULL,
    content text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id, mem_type)
);

CREATE TABLE skill_overrides (
    skill_id text PRIMARY KEY,
    name text,
    description text,
    triggers_json jsonb,
    core_markdown text,
    details_markdown text,
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE chat_sessions (
    session_id text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title text NOT NULL DEFAULT 'Новый чат',
    created_at timestamptz NOT NULL DEFAULT now(),
    last_access timestamptz NOT NULL DEFAULT now(),
    has_dataset boolean NOT NULL DEFAULT false,
    last_message_preview text,
    allow_auto_title boolean NOT NULL DEFAULT false,
    title_is_custom boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_chat_sessions_user
    ON chat_sessions(user_id, last_access DESC);

CREATE TABLE session_state (
    session_id text PRIMARY KEY REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    version bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE session_messages (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    message_index integer NOT NULL,
    role text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(session_id, message_index)
);

CREATE TABLE session_artifacts (
    artifact_id text PRIMARY KEY,
    session_id text NOT NULL REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    artifact_index integer NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(session_id, artifact_index)
);

CREATE TABLE session_memory (
    session_id text PRIMARY KEY REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE session_manifests (
    session_id text PRIMARY KEY REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    payload jsonb NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE session_notebooks (
    session_id text PRIMARY KEY REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    payload jsonb NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE stored_blobs (
    id uuid PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id text REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    kind text NOT NULL,
    logical_name text NOT NULL,
    media_type text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    sha256 text NOT NULL CHECK (length(sha256) = 64),
    content bytea NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz
);
CREATE INDEX idx_stored_blobs_session
    ON stored_blobs(session_id, kind, created_at DESC);
CREATE INDEX idx_stored_blobs_user
    ON stored_blobs(user_id, created_at DESC);
